### ISSUE TITLE
ErrorUrl not working / whitelist issue

### ISSUE THREAD

**Issue by gabn88** [manifoldjs/ManifoldCordova#94]
I get the following error when including the ErrorUrl preference:

W/HostedWebApp(16030): Whitelist rejection: url='file:///android_asset/www/offline.html'
W/System.err(16030): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=file:///android_asset/www/offline.html typ=text/html }
W/System.err(16030):    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1646)
W/System.err(16030):    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1438)
W/System.err(16030):    at android.app.Activity.startActivityForResult(Activity.java:3451)
W/System.err(16030):    at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:332)
W/System.err(16030):    at android.app.Activity.startActivityForResult(Activity.java:3412)
W/System.err(16030):    at android.app.Activity.startActivity(Activity.java:3654)
W/System.err(16030):    at android.app.Activity.startActivity(Activity.java:3622)
W/System.err(16030):    at com.manifoldjs.hostedwebapp.HostedWebApp.onOverrideUrlLoading(HostedWebApp.java:257)
W/System.err(16030):    at org.apache.cordova.PluginManager.onOverrideUrlLoading(PluginManager.java:452)
W/System.err(16030):    at org.apache.cordova.CordovaWebViewImpl$EngineClient.onNavigationAttempt(CordovaWebViewImpl.java:601)
W/System.err(16030):    at org.crosswalk.engine.XWalkCordovaResourceClient.shouldOverrideUrlLoading(XWalkCordovaResourceClient.java:99)
W/System.err(16030):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(16030):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(16030):    at org.xwalk.core.internal.ReflectMethod.invoke(ReflectMethod.java:61)
W/System.err(16030):    at org.xwalk.core.internal.XWalkResourceClientBridge.shouldOverrideUrlLoading(XWalkResourceClientBridge.java:224)
W/System.err(16030):    at org.xwalk.core.internal.XWalkResourceClientBridge.shouldOverrideUrlLoading(XWalkResourceClientBridge.java:214)
W/System.err(16030):    at org.xwalk.core.internal.XWalkContentsClientBridge.shouldOverrideUrlLoading(XWalkContentsClientBridge.java:209)
W/System.err(16030):    at org.xwalk.core.internal.XWalkContentsClientBridge$InterceptNavigationDelegateImpl.shouldIgnoreNavigation(XWalkContentsClientBridge.java:96)
W/System.err(16030):    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(16030):    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
W/System.err(16030):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(16030):    at android.os.Looper.loop(Looper.java:136)
W/System.err(16030):    at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err(16030):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(16030):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(16030):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
W/System.err(16030):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
W/System.err(16030):    at dalvik.system.NativeStart.main(Native Method)

**Comment by boyofgreen** [comment]
Hi @gabn88  sorry I missed this issue.   Are you still having this problem?  Do you have it without xwalk as well?

**Comment by gabn88** [comment]
Hi @boyofgreen, no problem!

I'm still having the issue. To be honoust I think it is really hard to use manifoldcordova in a production app. 

I get a lot of 'white pages of death', and because of this issue it is not possible style the white page of death.

For example, when the app is closed and restarted without internet access, you might see a white page, or an Application Error (no connection). If the internet connection is really slow/unstable you have more chance of getting a white page, but if the device is not connected to the internet at all you are more likely to get an Application Error.

Both cannot be suppressed with a custom page with a reload button, which would be necessary to make it production ready I think.
